#!/bin/bash
# DATABASE STUFF IS NOT BEING PICKED UP BY settings.py
# echo $BASH_VERSION
# These will be env vars in the runserver execution env
# local secret key
# generated this key here: https://miniwebtool.com/django-secret-key-generator/
export DJANGO_SECRET_KEY="dev_key_$ko1ridow#(0706$lk-luqgo(pq_$3)++q-gpad5o$c#q2)qlv"
export TEST_VAR="this is the test var value"
export DB_USER="mark"
export DB_PASSWORD="*WoYaoLai*"
# heroku postgresql
# export DATABASE_URL="postgres://mcbsrphpgaaabg:326bdb70df9cb0c2d5f253c59fb703717476d2007094c5b69726511bf23fed3a@ec2-34-231-63-30.compute-1.amazonaws.com:5432/daldjb47mffpgn"
# local postgresql
export DATABASE_URL="postgres://mark:*WoYaoLai*@localhost:5432/localhost_local_library"
# env vars set, start local server at localhost:8000 (django default)
python manage.py runserver

# New super user when connected to Heroku postgresql
# user: mark3
# password: *WoYaoLai*
# Above working with local postgres

